In [3]:
import pandas as pd
# Download and save the Parquet file
parquet_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"
df_green = pd.read_parquet(parquet_url)
df_green.to_parquet('green_tripdata_2025-11.parquet')

# Download and save the CSV file
csv_url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"
df_zones = pd.read_csv(csv_url)
df_zones.to_csv('taxi_zone_lookup.csv', index=False)

print("Files downloaded successfully!")

Files downloaded successfully!

In [4]:
df_green

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.20,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.20,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.50,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.70,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.40,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46907,2,2025-11-30 19:58:34,2025-11-30 20:14:28,NaN,NaN,59,51,NaN,8.50,33.22,...,0.5,0.00,0.0,NaN,1.0,34.72,NaN,NaN,NaN,0.00
46908,2,2025-11-30 19:34:00,2025-11-30 19:46:00,NaN,NaN,74,151,NaN,1.73,13.86,...,0.5,0.77,0.0,NaN,1.0,16.13,NaN,NaN,NaN,0.00
46909,2,2025-11-30 21:46:46,2025-11-30 22:17:55,NaN,NaN,33,163,NaN,7.52,38.42,...,0.5,1.00,0.0,NaN,1.0,44.42,NaN,NaN,NaN,0.75
46910,2,2025-11-30 21:00:00,2025-11-30 21:15:00,NaN,NaN,16,95,NaN,5.61,24.67,...,0.5,0.00,0.0,NaN,1.0,26.17,NaN,NaN,NaN,0.00
46911,2,2025-11-30 23:26:00,2025-11-30 23:42:00,NaN,NaN,65,87,NaN,2.91,14.46,...,0.5,3.89,0.0,NaN,1.0,23.35,NaN,NaN,NaN,0.75

In [6]:
df_zones

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                       NV          NaN
264         265        Unknown                      NaN          NaN

[265 rows x 4 columns]

## Question 3. Counting short trips

In [20]:
november = df_green[(df_green['lpep_pickup_datetime'] >= '2025-11-01') & (df_green['lpep_pickup_datetime'] < '2025-12-01')]
november[november['trip_distance'] <= 1]

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.20,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.0,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.20,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.0,0.0
8,2,2025-11-01 00:03:08,2025-11-01 00:06:27,N,1.0,223,223,1.0,0.63,5.10,...,0.5,1.52,0.0,NaN,1.0,9.12,1.0,1.0,0.0,0.0
11,2,2025-11-01 00:02:26,2025-11-01 00:02:31,N,5.0,93,93,1.0,0.00,28.00,...,0.0,5.80,0.0,NaN,1.0,34.80,1.0,2.0,0.0,0.0
14,2,2025-11-01 00:05:40,2025-11-01 00:05:45,N,5.0,244,244,1.0,0.00,9.50,...,0.0,2.10,0.0,NaN,1.0,12.60,1.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46789,6,2025-11-29 14:02:50,2025-11-29 14:08:07,NaN,NaN,188,188,NaN,0.95,2.90,...,0.5,0.00,0.0,NaN,0.3,16.00,NaN,NaN,NaN,0.0
46809,1,2025-11-29 17:02:56,2025-11-29 17:09:35,NaN,NaN,41,42,NaN,0.80,7.90,...,0.5,0.00,0.0,NaN,1.0,9.40,NaN,NaN,NaN,0.0
46824,2,2025-11-29 21:43:00,2025-11-29 21:52:00,NaN,NaN,145,226,NaN,0.00,13.02,...,0.5,4.36,0.0,NaN,1.0,18.88,NaN,NaN,NaN,0.0
46854,6,2025-11-30 10:30:57,2025-11-30 10:36:22,NaN,NaN,10,215,NaN,0.79,0.00,...,0.5,0.00,0.0,NaN,0.3,16.00,NaN,NaN,NaN,0.0
46876,6,2025-11-30 13:06:21,2025-11-30 13:11:39,NaN,NaN,7,260,NaN,0.67,5.80,...,0.5,0.00,0.0,NaN,0.3,16.00,NaN,NaN,NaN,0.0

## Question 4. Longest trip for each day

Which was the pick up day with the longest trip distance? Only consider trips with `trip_distance` less than 100 miles (to exclude data errors).

Use the pick up time for your calculations.

- 2025-11-14
- 2025-11-20
- 2025-11-23
- 2025-11-25

In [23]:
less_100 = november[november['trip_distance'] <= 100]
less_100.sort_values('trip_distance', ascending=False).head(1)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
18867,2,2025-11-14 15:36:27,2025-11-14 18:40:48,N,4.0,130,265,2.0,88.03,610.6,...,0.5,0.0,0.0,NaN,1.0,612.1,2.0,1.0,0.0,0.0

## Question 5. Biggest pickup zone

Which was the pickup zone with the largest `total_amount` (sum of all trips) on November 18th, 2025?

- East Harlem North
- East Harlem South
- Morningside Heights
- Forest Hills

In [39]:
november_18 = df_green[df_green['lpep_pickup_datetime'].dt.strftime('%Y-%m-%d') == '2025-11-18'][['PULocationID','total_amount']]
zone = november_18.merge(df_zones[['LocationID', 'Zone']],left_on = 'PULocationID',right_on ='LocationID')
zone

      PULocationID  total_amount  LocationID                      Zone
0               74         17.00          74         East Harlem North
1               75         17.10          75         East Harlem South
2               74         19.62          74         East Harlem North
3               74         11.00          74         East Harlem North
4               74         22.23          74         East Harlem North
...            ...           ...         ...                       ...
1768           236         46.87         236     Upper East Side North
1769           263         42.40         263            Yorkville West
1770           244         54.08         244  Washington Heights South
1771           166         21.53         166       Morningside Heights
1772            97         29.38          97               Fort Greene

[1773 rows x 4 columns]

In [43]:
zone.groupby('Zone')['total_amount'].sum().to_frame('Total_amount').reset_index().sort_values('Total_amount',ascending=False).head()

                         Zone  Total_amount
39          East Harlem North       9281.92
40          East Harlem South       6696.13
23               Central Park       2378.79
128  Washington Heights South       2139.05
85        Morningside Heights       2100.59

## Question 6. Largest tip

For the passengers picked up in the zone named "East Harlem North" in November 2025, which was the drop off zone that had the largest tip?

Note: it's `tip` , not `trip`. We need the name of the zone, not the ID.

- JFK Airport
- Yorkville West
- East Harlem North
- LaGuardia Airport

In [58]:
df_zones[df_zones['Zone'] == "East Harlem North"] 
### EHN have location ID = 74

    LocationID    Borough               Zone service_zone
73          74  Manhattan  East Harlem North    Boro Zone

In [62]:
ehn = november[november['PULocationID'] == 74][['DOLocationID','tip_amount']]
ehn_drop = ehn.merge(df_zones,left_on = 'DOLocationID',right_on ='LocationID')
ehn_drop.sort_values('tip_amount',ascending=False).head(1)

,DOLocationID,tip_amount,LocationID,Borough,Zone,service_zone
11613,263,81.89,263,Manhattan,Yorkville West,Yellow Zone